# Generated by Django 5.1.3 on 2025-04-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('ner', models.TextField()),
                ('directions', models.TextField()),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
