# Generated by Django 4.1.13 on 2025-05-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='clicked_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
